spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

application:
  delimiter: ";"
  locale: ru_RU
  file-name: /question-ru.csv

command:
  line:
    runner:
      enabled: false
  shell:
    runner:
      enabled: true