INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME, AGE, YEAR_BIRTHDATE) VALUES
    (
        100, 'Herbert', 'Shieldt', 72, 1951
    );

INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME, AGE, YEAR_BIRTHDATE) VALUES
    (
        200, 'Ivan', 'Efremov', 64, 1908
    );

INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME, AGE, YEAR_BIRTHDATE) VALUES
    (
        300, 'Isaac', 'Asimov', 72, 1919
    );

INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME, AGE, YEAR_BIRTHDATE) VALUES
    (
        400, 'Irvine', 'Welsh', 64, 1958
    );

INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME, AGE, YEAR_BIRTHDATE) VALUES
    (
        500, 'Lyubov', 'Voronkova', 70, 1906
    );