spring:
  shell:
    interactive:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testbookdb
#  sql:
#    init:
#      mode: always
#      data-locations: data2.sql
#      schema-locations: schema2.sql