spring:
  data:
    mongodb:
      username: springboot
      password: pivotal
      database: pps
      port: 27017
      host: localhost
      authentication-database: admin
      uri: mongodb://springboot:pivotal@localhost:27017/pps?authSource=admin&authMechanism=SCRAM-SHA-1


mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local