spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    user: sa
    password:

springdoc:
  packages-to-scan: ru.otus.page
  paths-to-match: /**

logging:
  level:
    org.springframework.web: DEBUG