spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:h2:mem:testdb
