spring:
  main.allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  data:
    mongodb:
      username: springboot
      password: pivotal
      host: localhost
      port: 27017
      database: griffins
      authentication-database: admin
      uri: mongodb://springboot:pivotal@localhost:27017/griffins?authSource=admin&authMechanism=SCRAM-SHA-1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local