DROP TABLE IF EXISTS BOOK_GENRE;
CREATE TABLE BOOK_GENRE
(
    BOOK_ID BIGINT,
    GENRE_ID BIGINT,
    CONSTRAINT FK_BOOK_GENRE_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    CONSTRAINT FK_BOOK_GENRE_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID),
    PRIMARY KEY (BOOK_ID, GENRE_ID)
);