INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (100, 900);
INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (100, 1000);

INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (200, 600);
INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (200, 700);
INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (200, 200);

INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (300, 600);
INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (300, 700);
INSERT INTO BOOK_GENRE (BOOK_ID, GENRE_ID) VALUES (300, 200);